config/routes.rb
Rails.application.routes.draw do
  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  delete 'carts/show'

  get '/gallery' => 'gallery#index'

  resources :products
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]

  root 'home#index'
  get '/store' => 'products#store'

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :order_status
  has_many :order_items
  before_create :set_order_status
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
  has_many :orders
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :order_items

  default_scope { where(active: true) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_order

  def current_order
    if !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil

    respond_to do |format|
      if (current_user.try(:admin?) || current_user.try(:employee?))
        format.html { redirect_to cart_path, notice: "Your cart is currently empty." }
      else
        format.html { redirect_to products_path, notice: "Your cart is currently empty." }
      end
      format.js
      format.json { head :no_content }
    end
  end
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
    def index
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end

end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def create
    @order = current_order
    @order_item = @order.order_items.new(order_item_params)
    @order.save
    session[:order_id] = @order.id
  end

  def update
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.update_attributes(order_item_params)
    @order_items = @order.order_items
  end

  def destroy
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = @order.order_items
  end
private
  def order_item_params
    params.require(:order_item).permit(:quantity, :product_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @order_item = current_order.order_items.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/_cart_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></h4>
    </div>
    <div class="col-xs-4">
      
      <%= form_for order_item, remote: true do |f| %>
        <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency order_item.unit_price %></span></h4>
        <div class="row">
          <div class="col-xs-4">
            <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
            <%= f.hidden_field :product_id, value: product.id %>
          </div>
          <div class="col-xs-8 text-right">
            <div class="btn-group">
              <%= f.submit "Update Quantity", class: "btn btn-primary" %>
              <%= link_to "Delete", order_item, { data: { confirm: "Are you sure you wish to delete the product '#{order_item.product.name}' from your cart?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
            </div>
          </div>
        </div>
        <h4 class="text-right">Total Price: <span style="color: green"><%= number_to_currency order_item.total_price %></span></h4>
      <% end %>
    </div>
    
  </div>
</div>

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @order_items.size == 0 %>
  <p class="text-center">
    There are no items in your shopping cart.  Please <%= link_to "go back", root_path %> and add some items to your cart.
  </p>
<% else %>
  <% @order_items.each do |order_item| %>
    <%= render 'carts/cart_row', product: order_item.product, order_item: order_item, show_total: true %>
  <% end %>
<% end %>

  <div class="checkout_btn">
  <div class="checkout_btn-back">
    <p>Are you sure you want to do that?</p>
    <button class="yes">Yes</button>
    <button class="no">No</button>
  </div>
  <div class="checkout_btn-front">CHECKOUT</div>
</div>

<%= javascript_include_tag 'main.js' %>

app/views/carts/show.html.erb
<div class="shopping-cart">
  <%= render "shopping_cart" %>
</div>

app/views/gallery/index.html.erb
<%= stylesheet_link_tag 'scrolla.css' %>


<div class="forsale">
	Images taken by drones
</div>
<br>
<div id="cbp-fbscroller" class="cbp-fbscroller">
	<section id="fbsection1"></section>
	<section id="fbsection2"></section>
	<section id="fbsection3"></section>
	<section id="fbsection4"></section>
	<section id="fbsection5"></section>
	<section id="fbsection6"></section>
	<section id="fbsection7"></section>
	<section id="fbsection8"></section>
	<section id="fbsection9"></section>
	<section id="fbsection10"></section>
</div>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>

<head>
<link href='http://fonts.googleapis.com/css?family=Cinzel:400,700,900' rel='stylesheet' type='text/css'>
</head>

<body data-no-turbolink='true'>

<video autoplay loop muted id="bgvid">

    <source src="/assets/dronevid3.mp4" type="video/mp4">
</video>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="droneshop">
	<strong>The Drone Shop</strong>
</div>
</body>
</html>

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.subtotal} )", cart_path, class: "btn btn-link" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dave's Drone Shop</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <% if request.ssl? %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <% else %> 
    <%= stylesheet_link_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <% end %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Architects+Daughter' rel='stylesheet' type='text/css'>
  
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="row">
 <img src="assets/droneicon.png" width="50px" height:"50px" style="float:left;margin-top:1.5%;" />
        <nav class="navigation">

          
          <div class="navlink">
              <li><h1>|<a href="/">Home</a>|</h1></li>
          </div>
          
          <div class="navlink">
              <li><h1 style="display:inline-block;">|<%= link_to "Store", products_path %>|</h1></li>
          </div>

          <div class="navlink">
              <li><h1 style="display:inline-block;">|<%= link_to "Gallery", gallery_path%>|</li>
          </div>

        </nav>

      <div class="navlink">
        <h1 class="cart-text">|<%= render 'layouts/cart_text' %>|</h1>
      </div>

        <img src="assets/droneicon.png" / width="50px" height:"50px" style="float:right;margin-top:1.5%;">

    </div>

    <%= yield %>
    <br>


</body>
</html>

app/views/order_items/create.html.erb
<h1>OrderItems#create</h1>
<p>Find me in app/views/order_items/create.html.erb</p>

app/views/order_items/create.js.erb
<% if @order.errors.any? || @order_item.errors.any? %>
alert("not valid.")
<% else %>
  $(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
<% end %>

app/views/order_items/destroy.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/order_items/update.html.erb
<h1>OrderItems#update</h1>
<p>Find me in app/views/order_items/update.html.erb</p>

app/views/order_items/update.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/products/_product_row.html.erb
    <div class="product">
      <img class="product__image" src="/assets<%= product.image_url %>" alt="Product 1" />

      <h4><%= product.name %></small></h4>
      <%= form_for order_item, remote: true do |f| %>
      <h4>Unit Price: <span style="color: green"><%= number_to_currency product.price %></span></h4>

          <div class="input-group">
            <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
            <div class="input-group-btn">
              <%= f.hidden_field :product_id, value: product.id %>
              <%= f.submit "Add to Cart", class: "btn btn-primary" %>
            </div>
          </div>

      <% end %>
    </div>

app/views/products/index.html.erb
<!DOCTYPE html>
<html>

<head>

  <title>Store</title>

</head>
<body>

<div class="forsale">
<strong>Products</strong>
</div>
<section class="grid">
<% @products.each do |product| %>

<%= render "product_row", product: product, order_item: @order_item %>

<% end %>
</section>


    
</body>
</html>